general {
    gaps_in = 5
    gaps_out = 8
    border_size = 2
    col.active_border = $primary
    col.inactive_border = $surface_container
    layout = dwindle
    resize_on_border = true
}

decoration {
    rounding = 14
    active_opacity = 0.93
    inactive_opacity = 0.75
#   screen_shader = ~/.config/hypr/shaders/sway.frag

    blur {
        enabled = true
        size = 8
        passes = 3
        vibrancy = 0.15
        vibrancy_darkness = 0.3
        noise = 0.008
        contrast = 0.9
        brightness = 0.9
        popups = true
        popups_ignorealpha = 0.3
    }

    shadow {
        enabled = false
    }
}
