# ── Path Definitions ───────────────────────────────────────
$hypr = $HOME/.config/hypr

# ── Global Variables ───────────────────────────────────────
$terminal    = kitty
$fileManager = thunar
$menu        = qs --path ~/.config/quickshell/components/Launcher/Luna.qml
$browser     = firefox
$scripts     = $hypr/scripts
$quickshell  = ~/.config/quickshell/components/
$mainMod     = SUPER

# ── Monitors ───────────────────────────────────────────────
monitor = eDP-1, 1920x1080@144, 0x0, 1
monitor = , preferred, auto, auto

# ── Source Modules ───────────────────────

source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/core/env.conf
source = ~/.config/hypr/core/input.conf

source = ~/.config/hypr/appearance/general.conf
source = ~/.config/hypr/animations/harmony.conf

source = ~/.config/hypr/behaivor/dwindle.conf
source = ~/.config/hypr/behaivor/misc.conf

source = ~/.config/hypr/sessions/start.conf
source = ~/.config/hypr/sessions/keys/vroomies.conf


