wallpaper {
    monitor = eDP-1
    path = ~/Pictures/Alice/Fixed/Algis.jpg
    fit_mode = cover
}

#wallpaper {
#    monitor = DP-2
#    path = ~/myFile2.jxl
#    fit_mode = cover
#}

# wallpaper {
#    monitor = 
#    path = ~/fallback.jxl
#   fit_mode = cover
#}


