general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = $primary
    col.inactive_border = rgba(595959aa)
    layout = master 
    resize_on_border = true
}

decoration {
    rounding = 12
    blur {
        enabled = true
        size = 8
        passes = 3
        vibrancy = 0.17
        new_optimizations = true
        ignore_opacity = true
        noise = 0.01
        contrast = 0.9
        xray = true
        popups = true
    }

    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(00000066)
    }
}

layerrule = blur, waybar
layerrule = ignorezero, waybar
layerrule = ignorealpha 0.5, waybar
layerrule = xray 1, waybar

layerrule = blur, swaync-control-center
layerrule = blur, swaync-notification-box
layerrule = ignorezero, swaync-control-center
layerrule = ignorezero, swaync-notification-box
layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-box

layerrule = blur, rofi
layerrule = ignorezero, rofi

master {
    mfact = 0.55
    orientation = left
    inherit_fullscreen = true
    special_scale_factor = 0.8
}

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    vrr = 1
}
