###################
### ANIMATIONS ###
###################
animations {
    enabled = true

    bezier = smooth, 0.2, 0.9, 0.1, 1.0
    bezier = overshot, 0.34, 1.56, 0.64, 1
    bezier = easeInExpo, 0.95, 0.05, 0.8, 0.04

    animation = windows, 1, 6, overshot, slide
    bezier = easeInExpo, 0.95, 0.05, 0.8, 0.04
    animation = border, 1, 6, smooth
    animation = fade, 1, 5, smooth
    animation = workspaces, 1, 7, overshot, slidevert
}
